### ISSUE TITLE
Avoid using strings and export as constants

### ISSUE THREAD

**Issue by uiyuvi** [naveen5765/berlin-clock#3]
https://github.com/naveen5765/berlin-clock/blob/8155cba5574aba7b659bbb545cdd9aef22a9fd32/src/BerlinClock.js#L4

**Comment by naveen5765** [comment]
added constants for each light state

export const LIGHT_OFF = 'O';
export const LIGHT_YELLOW = 'Y';
export const LIGHT_RED = 'R';

**Comment by uiyuvi** [comment]
Is it mentioned in requirement as light? Or lamp?
